/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mieditor;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author ciclos.pablo
 */
public class jfEditor extends javax.swing.JFrame {
    //Declaraciones
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfEditor.class.getName());
    File archivoIN;
 
    
    
    
    
//CONSTRUCTORES   
    public jfEditor() {
        initComponents();
        setTitle("PROCESADOR DE TEXTO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtflArchivoIn = new javax.swing.JTextField();
        jtflArchivoOut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtContenidoArchivoIn = new javax.swing.JTextArea();
        jbSalir = new javax.swing.JButton();
        jbIsArchivo = new javax.swing.JButton();
        jbIsDirectorio = new javax.swing.JButton();
        jbVerArchivoIn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtContenidoArchivoOut = new javax.swing.JTextArea();
        jbVerArchivoOut = new javax.swing.JButton();
        jbProcesar = new javax.swing.JButton();
        jbSeleccionarArchivoIn = new javax.swing.JButton();
        jbSeleccionarArchivoOut = new javax.swing.JButton();
        jbVerArchivoInBuffer = new javax.swing.JButton();
        jbVerArchivoOutBuffer = new javax.swing.JButton();
        jbProcesarBuffer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROCESADOR DE TEXTO");

        jLabel2.setText("Archivo In: ");

        jLabel3.setText("Archivo Out:");

        jtflArchivoOut.addActionListener(this::jtflArchivoOutActionPerformed);

        jtContenidoArchivoIn.setColumns(20);
        jtContenidoArchivoIn.setRows(5);
        jScrollPane1.setViewportView(jtContenidoArchivoIn);

        jbSalir.setText("Salir");

        jbIsArchivo.setText("Es archivo?");
        jbIsArchivo.addActionListener(this::jbIsArchivoActionPerformed);

        jbIsDirectorio.setText("Es directorio?");
        jbIsDirectorio.addActionListener(this::jbIsDirectorioActionPerformed);

        jbVerArchivoIn.setText("Leer");
        jbVerArchivoIn.addActionListener(this::jbVerArchivoInActionPerformed);

        jtContenidoArchivoOut.setColumns(20);
        jtContenidoArchivoOut.setRows(5);
        jScrollPane2.setViewportView(jtContenidoArchivoOut);

        jbVerArchivoOut.setText("Leer");
        jbVerArchivoOut.addActionListener(this::jbVerArchivoOutActionPerformed);

        jbProcesar.setText("Procesar");
        jbProcesar.addActionListener(this::jbProcesarActionPerformed);

        jbSeleccionarArchivoIn.setText("...");
        jbSeleccionarArchivoIn.addActionListener(this::jbSeleccionarArchivoInActionPerformed);

        jbSeleccionarArchivoOut.setText("...");
        jbSeleccionarArchivoOut.addActionListener(this::jbSeleccionarArchivoOutActionPerformed);

        jbVerArchivoInBuffer.setText("Leer ArchivoIN");
        jbVerArchivoInBuffer.addActionListener(this::jbVerArchivoInBufferActionPerformed);

        jbVerArchivoOutBuffer.setText("Leer ArchivoOut");
        jbVerArchivoOutBuffer.addActionListener(this::jbVerArchivoOutBufferActionPerformed);

        jbProcesarBuffer.setText("Procesar");
        jbProcesarBuffer.addActionListener(this::jbProcesarBufferActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtflArchivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbSeleccionarArchivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbVerArchivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbIsArchivo)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbIsDirectorio)))))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtflArchivoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbSeleccionarArchivoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbVerArchivoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbProcesarBuffer)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbVerArchivoInBuffer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jbVerArchivoOutBuffer))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jbProcesar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProcesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtflArchivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jtflArchivoOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbVerArchivoOut)
                        .addComponent(jbSeleccionarArchivoIn)
                        .addComponent(jbSeleccionarArchivoOut))
                    .addComponent(jbVerArchivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIsArchivo)
                    .addComponent(jbIsDirectorio)
                    .addComponent(jbVerArchivoInBuffer)
                    .addComponent(jbVerArchivoOutBuffer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbProcesarBuffer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIsArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIsArchivoActionPerformed
        archivoIN = new File(jtflArchivoIn.getText());
        if (archivoIN.exists()) {
            jtContenidoArchivoIn.append("Es una Archivo?: "+archivoIN.isFile()+"\n");
        }else{
            jtContenidoArchivoIn.append("No existe");
        }
        
    }//GEN-LAST:event_jbIsArchivoActionPerformed

    private void jbIsDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIsDirectorioActionPerformed
        archivoIN = new File(jtflArchivoIn.getText());
        if (archivoIN.exists()) {
            jtContenidoArchivoIn.append("Es un Directorio?: "+archivoIN.isDirectory()+"\n");
        }else{
            jtContenidoArchivoIn.append("No existe");
        }
        
    }//GEN-LAST:event_jbIsDirectorioActionPerformed

    private void jbProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcesarActionPerformed
        String nombreArchivoIn;
        String nombreArchivoOut;
        nombreArchivoIn = jtflArchivoIn.getText();
        nombreArchivoOut = jtflArchivoOut.getText();
        File archivo = new File(nombreArchivoOut);
        jtContenidoArchivoIn.setText("");
        jtContenidoArchivoOut.setText("");
        
        while (!archivo.exists()) {
            try{
                archivo.createNewFile();
            }catch(IOException e){
                jtContenidoArchivoOut.setText("Error E/S: " + e);
            }
        }
        
            
            if (jtflArchivoIn.getText().contains(".txt")) {
            try {
            FileReader archR = new FileReader(nombreArchivoIn);
            FileWriter archW = new FileWriter(nombreArchivoOut);
            
            int valor = archR.read();
            
            while(valor!=-1){
                
                jtContenidoArchivoIn.append(String.valueOf((char)valor));
                
                archW.write(valor);
                valor = archR.read();
                
            }
            archR.close();
            archW.close();
            
            
            }catch(IOException e){
            jtContenidoArchivoIn.setText("Error E/S: " + e); 
            }
        
            try {
            FileReader archR2 = new FileReader(nombreArchivoOut);
            int valor2 = archR2.read();
            
            while(valor2!=-1){
                jtContenidoArchivoOut.append(String.valueOf((char)valor2));
                valor2 = archR2.read();
            }
            archR2.close();
            }catch(IOException e){
            jtContenidoArchivoOut.setText("Error E/S: " + e);
            }
        }
        
           
        if (jtflArchivoIn.getText().contains(".jpg")) {
            try {
            FileInputStream archRB = new FileInputStream(nombreArchivoIn);
            FileOutputStream archWB = new FileOutputStream(nombreArchivoOut);
            
            int valor = archRB.read();
            
            while(valor!=-1){
                
                archWB.write(valor);
               
                valor = archRB.read();
                
            }
            archRB.close();
            archWB.close();
            
            } catch(IOException e){
            jtContenidoArchivoIn.setText("Error E/S: " + e);
            
            }
        }
            
    
        
        
        
        
    }//GEN-LAST:event_jbProcesarActionPerformed

    private void jbVerArchivoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerArchivoInActionPerformed
        jtContenidoArchivoIn.setText("");
        String nombreArchivoIn;
        String nombreArchivoOut;
        nombreArchivoIn = jtflArchivoIn.getText();
        nombreArchivoOut = jtflArchivoOut.getText();
        
        if (jtflArchivoIn.getText().contains(".txt")) {
            try {
            FileReader archR = new FileReader(nombreArchivoIn);
            
            int valor = archR.read();
            
            while(valor!=-1){
                
                jtContenidoArchivoIn.append(String.valueOf((char)valor));
               
                valor = archR.read();
                
            }
            archR.close();
            
            } catch(IOException e){
            jtContenidoArchivoIn.setText("Error E/S: " + e);
            
            }
        }
        
        if (jtflArchivoIn.getText().contains(".jpg")||jtflArchivoIn.getText().contains(".png")) {
            try {
            FileInputStream archRB = new FileInputStream(nombreArchivoIn);
            FileOutputStream archWB = new FileOutputStream(nombreArchivoOut);
            
            int valor = archRB.read();
            jtContenidoArchivoIn.setText("El archivo se está copiando");
            while(valor!=-1){
                
                archWB.write(valor);
               
                valor = archRB.read();
                
            }
            jtContenidoArchivoOut.setText("Archivo clonado correctamente");
            archRB.close();
            archWB.close();
            
            } catch(IOException e){
            jtContenidoArchivoIn.setText("Error E/S: " + e);
            
            }
        }
          
    }//GEN-LAST:event_jbVerArchivoInActionPerformed

    private void jbVerArchivoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerArchivoOutActionPerformed
        jtContenidoArchivoOut.setText("");
        String nombreArchivoOut;
        nombreArchivoOut = jtflArchivoOut.getText();
        
        try {
            FileReader archR2 = new FileReader(nombreArchivoOut);
            int valor2 = archR2.read();
            
            while(valor2!=-1){
                jtContenidoArchivoOut.append(String.valueOf((char)valor2));
                valor2 = archR2.read();
            }
            archR2.close();
        }catch(IOException e){
            jtContenidoArchivoOut.setText("Error E/S: " + e);
        }
    }//GEN-LAST:event_jbVerArchivoOutActionPerformed

    private void jbSeleccionarArchivoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarArchivoInActionPerformed
        JFileChooser chooser =  new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jtflArchivoIn.setText(chooser.getSelectedFile().getPath());
        }
        
    }//GEN-LAST:event_jbSeleccionarArchivoInActionPerformed

    private void jtflArchivoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtflArchivoOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtflArchivoOutActionPerformed

    private void jbSeleccionarArchivoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarArchivoOutActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jtflArchivoOut.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jbSeleccionarArchivoOutActionPerformed

    private void jbVerArchivoInBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerArchivoInBufferActionPerformed
        jtContenidoArchivoIn.setText("");
        String nombreArchivoInBuffer;
        nombreArchivoInBuffer = jtflArchivoIn.getText();
        File archivoInBuffer = new File(nombreArchivoInBuffer);
        boolean eof = false;
        String lineaLeida = "";
        
        try {
            BufferedReader lectorMejorado = new BufferedReader(new FileReader(archivoInBuffer));
            while(!eof){
                lineaLeida = lectorMejorado.readLine();
                if (lineaLeida != null) {
                    jtContenidoArchivoIn.append(lineaLeida+"\n");
                }else{
                    eof = true;
                }
            }
            lectorMejorado.close();
        } catch (FileNotFoundException ex) {
            System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jbVerArchivoInBufferActionPerformed

    private void jbProcesarBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcesarBufferActionPerformed

        String nombreArchivoInBuffer;
        String nombreArchivoOutBuffer;
        nombreArchivoInBuffer=jtflArchivoIn.getText();
        nombreArchivoOutBuffer=jtflArchivoOut.getText();
        File archivoInBuffer = new File(nombreArchivoInBuffer);
        File archivoOutBuffer = new File(nombreArchivoOutBuffer);
        boolean eof = false;
        String lineaLeida = "";
        jtContenidoArchivoOut.setText("");
        File archivo = new File(nombreArchivoOutBuffer);
        
        while (!archivo.exists()) {
            try{
                archivo.createNewFile();
            }catch(IOException e){
                jtContenidoArchivoOut.setText("Error E/S: " + e);
            }
        }
            if (jtflArchivoIn.getText().contains(".txt")) {
              try {
            BufferedReader lectorMejorado = new BufferedReader(new FileReader(archivoInBuffer));
            BufferedWriter escritorMejorado = new BufferedWriter(new FileWriter(archivoOutBuffer)); 
            while(!eof){
                lineaLeida = lectorMejorado.readLine();
                if (lineaLeida != null) {
                    jtContenidoArchivoOut.append(lineaLeida+"\n");
                    escritorMejorado.write(lineaLeida+"\n");
                }else{
                    eof = true;
                }
            }
            lectorMejorado.close();
            escritorMejorado.close();
            } catch (FileNotFoundException ex) {
                System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (IOException ex) {
                System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }  
            }
            
            if (jtflArchivoIn.getText().contains(".jpg")||jtflArchivoIn.getText().contains(".png")) {
            try {
            BufferedInputStream lectorBitsMejorado = new BufferedInputStream(new FileInputStream(archivoInBuffer));
            BufferedOutputStream escritorBitsMejorado = new BufferedOutputStream(new FileOutputStream(archivoOutBuffer));
            
            int unByte;
            
            jtContenidoArchivoIn.setText("El archivo se está copiando");
            
            while((unByte=lectorBitsMejorado.read())!=-1){
                
                escritorBitsMejorado.write(unByte);
               
                
                
            }
            jtContenidoArchivoOut.setText("Archivo copiado correctamente");
            lectorBitsMejorado.close();
            escritorBitsMejorado.close();
            
            } catch(IOException e){
            jtContenidoArchivoIn.setText("Error E/S: " + e);
            
            }
        }
        
        
        
    }//GEN-LAST:event_jbProcesarBufferActionPerformed

    private void jbVerArchivoOutBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerArchivoOutBufferActionPerformed
        jtContenidoArchivoOut.setText("");
        String nombreArchivoOutBuffer;
        nombreArchivoOutBuffer = jtflArchivoOut.getText();
        File archivoOutBuffer = new File(nombreArchivoOutBuffer);
        boolean eof = false;
        String lineaLeida = "";
        try {
            BufferedReader lectorMejorado = new BufferedReader(new FileReader(archivoOutBuffer));
            while(!eof){
                lineaLeida = lectorMejorado.readLine();
                if (lineaLeida != null) {
                    jtContenidoArchivoOut.append(lineaLeida+"\n");
                }else{
                    eof = true;
                }
            }
            lectorMejorado.close();
        } catch (FileNotFoundException ex) {
            System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(jfEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jbVerArchivoOutBufferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfEditor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbIsArchivo;
    private javax.swing.JButton jbIsDirectorio;
    private javax.swing.JButton jbProcesar;
    private javax.swing.JButton jbProcesarBuffer;
    private javax.swing.JButton jbSalir;
    public javax.swing.JButton jbSeleccionarArchivoIn;
    private javax.swing.JButton jbSeleccionarArchivoOut;
    public javax.swing.JButton jbVerArchivoIn;
    private javax.swing.JButton jbVerArchivoInBuffer;
    private javax.swing.JButton jbVerArchivoOut;
    private javax.swing.JButton jbVerArchivoOutBuffer;
    private javax.swing.JTextArea jtContenidoArchivoIn;
    private javax.swing.JTextArea jtContenidoArchivoOut;
    private javax.swing.JTextField jtflArchivoIn;
    private javax.swing.JTextField jtflArchivoOut;
    // End of variables declaration//GEN-END:variables
}
