/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metodoburbuja;

/* Hola */

/* Hola */

import java.awt.Color;
import static java.awt.Color.white;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ciclos.pablo
 */
public class jFIncio extends javax.swing.JFrame {
    JTextField[] panelOriginal;
    JTextField[] panelOrdenado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jFIncio.class.getName());

    //Constructores
    public jFIncio() {
        setTitle("Método Burbuja");
        initComponents();
        setLocationRelativeTo(null);
        init();
        setLocationRelativeTo(null);
        
        
    }
    
    public void init(){
        String inputValue = JOptionPane.showInputDialog("¿Cuantos números quieres?");
        final int ancho=40;
        final int alto=40;
        final int disInicio=50;
        //Inicializamos los paneles
        
        panelOriginal = new JTextField[Integer.parseInt(inputValue)];
        panelOrdenado = new JTextField[Integer.parseInt(inputValue)];
        
        //Dibujamos los paneles
        
        for (int i = 0; i < panelOriginal.length; i++) {
            panelOriginal[i]=new JTextField();
            panelOriginal[i].setBounds(170,disInicio+(i*alto),ancho,alto);
            add(panelOriginal[i]);
            panelOriginal[i].setVisible(true);
            
            panelOrdenado[i]=new JTextField();
            panelOrdenado[i].setBounds(220,disInicio+(i*alto),ancho,alto);
            add(panelOrdenado[i]);
            panelOrdenado[i].setVisible(false);
            
            panelOrdenado[i].setBackground(Color.decode("#71c4ef"));
        }
        
        this.setSize(300, panelOriginal.length*alto+disInicio*2);
        
        
        
        //Le damos valor random de 0 a 100.
        Random rand=new Random();
        
        int [] num=new int[panelOriginal.length];
            
        for (int i = 0; i < num.length; i++) {
            num[i]=rand.nextInt(100);
        }
        
        for (int i = 0; i < panelOriginal.length; i++) {
            panelOriginal[i].setText(num[i]+"");
            panelOrdenado[i].setText(num[i]+"");
        }
       
    }
    
    public void ordenar(){
        
        for (int i = 0; i < panelOrdenado.length; i++) {
            panelOrdenado[i].setVisible(true);
            panelOrdenado[i].setBackground(Color.decode("#71c4ef"));
            for (int j = 0; j < panelOrdenado.length-1; j++) {
                int sValor;
                int sValor2;
                sValor=Integer.parseInt(panelOrdenado[j].getText());
                sValor2=Integer.parseInt(panelOrdenado[j+1].getText());
                if (sValor>sValor2) {
                    panelOrdenado[j+1].setText(sValor+"");
                    panelOrdenado[j].setText(sValor2+"");
                }
            }
        }         
    }
    
    public void resetear(){
        for (int i = 0; i < panelOrdenado.length; i++) {
            panelOrdenado[i].setText(panelOriginal[i].getText());
            panelOrdenado[i].setBackground(white);
        }
    }
    
    public void nuevo(){
        Random rand=new Random();
        
        int [] num1=new int[panelOriginal.length];
            
        for (int i = 0; i < num1.length; i++) {
            num1[i]=rand.nextInt(100);
        }
        
        for (int i = 0; i < panelOriginal.length; i++) {
            panelOrdenado[i].setBackground(white);
            panelOriginal[i].setText(num1[i]+"");
            panelOrdenado[i].setText(num1[i]+"");
        }
           
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInicio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBInicio.setBackground(new java.awt.Color(0, 119, 194));
        jBInicio.setText("Ordenar ");
        jBInicio.addActionListener(this::jBInicioActionPerformed);
        getContentPane().add(jBInicio);
        jBInicio.setBounds(23, 45, 130, 130);

        jButton1.setBackground(new java.awt.Color(89, 165, 242));
        jButton1.setText("Resetear");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(23, 180, 130, 23);

        jButton2.setBackground(new java.awt.Color(200, 255, 255));
        jButton2.setText("Nuevo");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2);
        jButton2.setBounds(23, 210, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        ordenar();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nuevo();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jFIncio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
