/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metodoburbuja;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ciclos.pablo
 */
public class jFIncio extends javax.swing.JFrame {
    JTextField[] panelOriginal;
    JTextField[] panelOrdenado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jFIncio.class.getName());

    //Constructores
    public jFIncio() {
        
        initComponents();
        setLocationRelativeTo(null);
        init();
        
        
    }
    
    public void init(){
        String inputValue = JOptionPane.showInputDialog("Please input a value");
        final int ancho=40;
        final int alto=40;
        final int disInicio=50;
        //Inicializamos los paneles
        
        panelOriginal = new JTextField[Integer.parseInt(inputValue)];
        panelOrdenado = new JTextField[Integer.parseInt(inputValue)];
        
        //Dibujamos los paneles
        
        for (int i = 0; i < panelOriginal.length; i++) {
            panelOriginal[i]=new JTextField();
            panelOriginal[i].setBounds(170,disInicio+(i*alto),ancho,alto);
            add(panelOriginal[i]);
            panelOriginal[i].setVisible(true);
            
            panelOrdenado[i]=new JTextField();
            panelOrdenado[i].setBounds(220,disInicio+(i*alto),ancho,alto);
            add(panelOrdenado[i]);
            panelOrdenado[i].setVisible(true);
        }
        
        this.setSize(300, panelOriginal.length*alto+disInicio*2);
        
        
        
        //Le damos valor random de 0 a 10.
        Random rand=new Random();
        int [] num=new int[panelOriginal.length];
        int [] numOrde=new int[panelOriginal.length];
        
        
        for (int i = 0; i < num.length; i++) {
            num[i]=rand.nextInt(10);
        }
        numOrde=num;
        
        for (int i = 0; i < panelOriginal.length; i++) {
            panelOriginal[i].setText(num[i]+"");
            panelOrdenado[i].setText(num[i]+"");
        }
       
    }
    
    private void burbuja(){
        for (int i = 0; i < panelOrdenado.length; i++) {
            for (int j = 0; j < panelOrdenado.length-1; j++) {
                int sValor;
                int sValor2;
                sValor=Integer.parseInt(panelOrdenado[i].getText());
                sValor2=Integer.parseInt(panelOrdenado[i+1].getText());
                if (sValor>sValor2) {
                    panelOrdenado[i+1].setText(sValor+"");
                    panelOrdenado[i].setText(sValor2+"");
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(this::jBInicioActionPerformed);
        getContentPane().add(jBInicio);
        jBInicio.setBounds(23, 45, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        burbuja();
    }//GEN-LAST:event_jBInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jFIncio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicio;
    // End of variables declaration//GEN-END:variables
}
