/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metodoburbuja;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ciclos.pablo
 */
public class jFIncio extends javax.swing.JFrame {
    JTextField[] panelOriginal;
    JTextField[] panelOrdenado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jFIncio.class.getName());

    //Constructores
    public jFIncio() {
        initComponents();
        init();
        
    }
    
    public void init(){
        String inputValue = JOptionPane.showInputDialog("Please input a value");
        
        //Inicializamos los paneles
        
        panelOriginal = new JTextField[Integer.parseInt(inputValue)];
        panelOrdenado = new JTextField[Integer.parseInt(inputValue)];
        
        //Dibujamos los paneles
        
        for (int i = 0; i <= panelOriginal.length; i++) {
            panelOriginal[i]=new JTextField();
            panelOriginal[i].setBounds(100,20+(i*10),10,10);
            add(panelOriginal[i]);
            panelOriginal[i].setVisible(true);
            
            panelOrdenado[i]=new JTextField();
            panelOrdenado[i].setBounds(130,20+(i*10),10,10);
            add(panelOrdenado[i]);
            panelOrdenado[i].setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jFIncio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
