/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Color;

/**
 *
 * @author ciclos.pablo
 */
public class jfCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfCalculadora.class.getName());

    public jfCalculadora() {
        setTitle("Calculadora v1.0");
        initComponents();
        setLocationRelativeTo(null);
        setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtPanel = new javax.swing.JTextField();
        jbLimpiarTodo = new javax.swing.JButton();
        jbBorrarCaracter = new javax.swing.JButton();
        jbCambiarSimbolo = new javax.swing.JButton();
        jbDivision = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jbMultiplicacion = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jbResta = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jbSuma = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbComa = new javax.swing.JButton();
        jbIgual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        jtPanel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtPanel.addActionListener(this::jtPanelActionPerformed);

        jbLimpiarTodo.setBackground(new java.awt.Color(212, 234, 247));
        jbLimpiarTodo.setText("AC");
        jbLimpiarTodo.addActionListener(this::jbLimpiarTodoActionPerformed);

        jbBorrarCaracter.setBackground(new java.awt.Color(212, 234, 247));
        jbBorrarCaracter.setText("<<");
        jbBorrarCaracter.addActionListener(this::jbBorrarCaracterActionPerformed);

        jbCambiarSimbolo.setBackground(new java.awt.Color(212, 234, 247));
        jbCambiarSimbolo.setText("+/-");
        jbCambiarSimbolo.addActionListener(this::jbCambiarSimboloActionPerformed);

        jbDivision.setBackground(new java.awt.Color(182, 204, 216));
        jbDivision.setText("/");
        jbDivision.addActionListener(this::jbDivisionActionPerformed);

        jb7.setBackground(new java.awt.Color(113, 196, 239));
        jb7.setText("7");
        jb7.addActionListener(this::jb7ActionPerformed);

        jb8.setBackground(new java.awt.Color(113, 196, 239));
        jb8.setText("8");
        jb8.addActionListener(this::jb8ActionPerformed);

        jb9.setBackground(new java.awt.Color(113, 196, 239));
        jb9.setText("9");
        jb9.addActionListener(this::jb9ActionPerformed);

        jbMultiplicacion.setBackground(new java.awt.Color(182, 204, 216));
        jbMultiplicacion.setText("*");
        jbMultiplicacion.addActionListener(this::jbMultiplicacionActionPerformed);

        jb4.setBackground(new java.awt.Color(113, 196, 239));
        jb4.setText("4");
        jb4.addActionListener(this::jb4ActionPerformed);

        jb5.setBackground(new java.awt.Color(113, 196, 239));
        jb5.setText("5");
        jb5.addActionListener(this::jb5ActionPerformed);

        jb6.setBackground(new java.awt.Color(113, 196, 239));
        jb6.setText("6");
        jb6.addActionListener(this::jb6ActionPerformed);

        jbResta.setBackground(new java.awt.Color(182, 204, 216));
        jbResta.setText("-");
        jbResta.addActionListener(this::jbRestaActionPerformed);

        jb1.setBackground(new java.awt.Color(113, 196, 239));
        jb1.setText("1");
        jb1.addActionListener(this::jb1ActionPerformed);

        jb2.setBackground(new java.awt.Color(113, 196, 239));
        jb2.setText("2");
        jb2.addActionListener(this::jb2ActionPerformed);

        jb3.setBackground(new java.awt.Color(113, 196, 239));
        jb3.setText("3");
        jb3.addActionListener(this::jb3ActionPerformed);

        jbSuma.setBackground(new java.awt.Color(182, 204, 216));
        jbSuma.setText("+");
        jbSuma.addActionListener(this::jbSumaActionPerformed);

        jb0.setBackground(new java.awt.Color(113, 196, 239));
        jb0.setText("0");
        jb0.addActionListener(this::jb0ActionPerformed);

        jbComa.setBackground(new java.awt.Color(113, 196, 239));
        jbComa.setText(",");
        jbComa.addActionListener(this::jbComaActionPerformed);

        jbIgual.setBackground(new java.awt.Color(245, 244, 241));
        jbIgual.setText("=");
        jbIgual.addActionListener(this::jbIgualActionPerformed);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(153, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBorrarCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCambiarSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jb0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrarCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCambiarSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbComa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPanelActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        jtPanel.setText(jtPanel.getText()+("0"));
        
    }//GEN-LAST:event_jb0ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        jtPanel.setText(jtPanel.getText()+("1"));
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        jtPanel.setText(jtPanel.getText()+("2"));
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        jtPanel.setText(jtPanel.getText()+("3"));
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        jtPanel.setText(jtPanel.getText()+("4"));
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        jtPanel.setText(jtPanel.getText()+("5"));
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        jtPanel.setText(jtPanel.getText()+("6"));
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        jtPanel.setText(jtPanel.getText()+("7"));
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        jtPanel.setText(jtPanel.getText()+("8"));
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        jtPanel.setText(jtPanel.getText()+("9"));
    }//GEN-LAST:event_jb9ActionPerformed

    private void jbComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComaActionPerformed
        jtPanel.setText(jtPanel.getText()+("."));
    }//GEN-LAST:event_jbComaActionPerformed

    private void jbLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTodoActionPerformed
        jtPanel.setText("");
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_jbLimpiarTodoActionPerformed

    private void jbSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSumaActionPerformed
        jLabel1.setText(jtPanel.getText());
        jLabel2.setText("+");
        jtPanel.setText("");
    }//GEN-LAST:event_jbSumaActionPerformed

    private void jbRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRestaActionPerformed
        jLabel1.setText(jtPanel.getText());
        jLabel2.setText("-");
        jtPanel.setText("");
    }//GEN-LAST:event_jbRestaActionPerformed

    private void jbMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicacionActionPerformed
        jLabel1.setText(jtPanel.getText());
        jLabel2.setText("*");
        jtPanel.setText("");
    }//GEN-LAST:event_jbMultiplicacionActionPerformed

    private void jbDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivisionActionPerformed
        jLabel1.setText(jtPanel.getText());
        jLabel2.setText("/");
        jtPanel.setText("");
    }//GEN-LAST:event_jbDivisionActionPerformed

    private void jbIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIgualActionPerformed
        double iVariable1;
        double iVariable2;

        double iResultado;
        String sResultadoFinal;

        if (jtPanel.getText().isEmpty()) {
            
        }else{
            iVariable1=Double.valueOf(jLabel1.getText());
            iVariable2=Double.valueOf(jtPanel.getText());
            switch (jLabel2.getText()){
                case "+":
                    jLabel3.setText(jtPanel.getText());
                    iResultado=iVariable1+iVariable2;
                    sResultadoFinal=String.format("%.2f",iResultado);
                    jtPanel.setText(sResultadoFinal);
                break;
            
                case "-":
                    jLabel3.setText(jtPanel.getText());
                    iResultado=iVariable1-iVariable2;
                    sResultadoFinal=String.format("%.2f",iResultado);
                    jtPanel.setText(sResultadoFinal);
                break;
            
                case "*":
                    jLabel3.setText(jtPanel.getText());
                    iResultado=iVariable1*iVariable2;
                    sResultadoFinal=String.format("%.2f",iResultado);
                    jtPanel.setText(sResultadoFinal);
                break;
            
                case "/":
                    if (iVariable2==0) {
                        jLabel3.setText(jtPanel.getText());
                        jtPanel.setText("Error: div/0");
                    }else{
                        jLabel3.setText(jtPanel.getText());
                        iResultado=iVariable1/iVariable2;
                        sResultadoFinal=String.format("%.2f",iResultado);
                        jtPanel.setText(sResultadoFinal);
                    }
                    
                break;
            }
        }
    }//GEN-LAST:event_jbIgualActionPerformed

    private void jbBorrarCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarCaracterActionPerformed
        
        if (jtPanel.getText().equals("")) {
            jtPanel.setText("");
        }else{
            String sVariablePanel=jtPanel.getText();
            String sVariableNueva=sVariablePanel.substring(0, sVariablePanel.length() -1);
            jtPanel.setText(sVariableNueva);
        }
    }//GEN-LAST:event_jbBorrarCaracterActionPerformed

    private void jbCambiarSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarSimboloActionPerformed
        String sNuevo=jtPanel.getText();
        double iNuevo=Double.parseDouble(sNuevo);
        double iNuevo2;
        
        if (iNuevo>0) {
            iNuevo2=iNuevo-(iNuevo*2);
            String sNuevo2=String.valueOf(iNuevo2);
            jtPanel.setText(sNuevo2);
        }
        if (iNuevo<0) {
            iNuevo2=Math.abs(iNuevo);
            String sNuevo2=String.valueOf(iNuevo2);
            jtPanel.setText(sNuevo2);
        }
    }//GEN-LAST:event_jbCambiarSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbBorrarCaracter;
    private javax.swing.JButton jbCambiarSimbolo;
    private javax.swing.JButton jbComa;
    private javax.swing.JButton jbDivision;
    private javax.swing.JButton jbIgual;
    private javax.swing.JButton jbLimpiarTodo;
    private javax.swing.JButton jbMultiplicacion;
    private javax.swing.JButton jbResta;
    private javax.swing.JButton jbSuma;
    private javax.swing.JTextField jtPanel;
    // End of variables declaration//GEN-END:variables
}
